#!/bin/bash

DEST=api.html

swift build
.build/debug/perfectapigen --root /Users/jonathanguthrie/Documents/Perfect-Collection/PerfectAPIClones --dest ${DEST} --template /Users/jonathanguthrie/Documents/Perfect-Collection/PerfectAPIGenerator/api_html.mustache

